package controller;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class SidebarController {
	private MainPageController mainController;
	
	public void setMainController(MainPageController controller) {
		this.mainController = controller;
	}

	// Event Listener on Button.onAction
	@FXML
	public void dashboardClicked(ActionEvent event) {
		// TODO Autogenerated
		mainController.loadPage("Dashboard.fxml");

	}
	// Event Listener on Button.onAction
	@FXML
	public void doctorsClicked(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("Doctor page");

	}
	// Event Listener on Button.onAction
	@FXML
	public void patientsClicked(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("Patients page");

	}
	// Event Listener on Button.onAction
	@FXML
	public void medicalClicked(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("Medical page");

	}
	// Event Listener on Button.onAction
	@FXML
	public void laboratoriesClicked(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("Laboratories page");

	}
	// Event Listener on Button.onAction
	@FXML
	public void facilitiesClicked(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("Facilities page");

	}
	// Event Listener on Button.onAction
	@FXML
	public void staffClicked(ActionEvent event) {
		// TODO Autogenerated
		mainController.loadPage("Staff.fxml");

	}
	// Event Listener on Button.onAction
	@FXML
	public void exitClicked(ActionEvent event) {
		// TODO Autogenerated
		System.exit(0);

	}
}
