package controller;

import javafx.fxml.FXML;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.VBox;
import model.Staff;
import services.StaffService;

import java.util.ArrayList;

import javafx.collections.FXCollections;
import javafx.event.ActionEvent;

public class StaffController {
	@FXML
	VBox mainContent;
	
	private StaffService staffService;
	
	public void setHospitalManagement(HospitalManagement hospital) {
        staffService = new StaffService(hospital);
    }

	// Event Listener on Button.onAction
	@FXML
	public void addStaffClicked(ActionEvent event) {
		mainContent.getChildren().clear();
		
		TextField idField = new TextField();
		idField.setPromptText("Staff ID");
		
		TextField nameField = new TextField();
		nameField.setPromptText("Name");
		
		TextField designationField = new TextField();
		designationField.setPromptText("Designation");
		
		TextField sexField = new TextField();
		sexField.setPromptText("Sex");
		
		TextField salaryField = new TextField();
		salaryField.setPromptText("Salary");

		Button addButton = new Button("Add Staff");
		addButton.setPrefWidth(120);
		addButton.setPrefHeight(40);

		addButton.setMinWidth(120);
		addButton.setMaxWidth(120);

		addButton.setMinHeight(40);
		addButton.setMaxHeight(40);
		
		addButton.setAlignment(Pos.CENTER);
		
		addButton.setOnAction(e -> {
			String id = idField.getText();
	        String name = nameField.getText();
	        String designation = nameField.getText();
	        String sex = sexField.getText();
	        int salary = Integer.parseInt(salaryField.getText());
	        
	        Staff staff = new Staff(id, name, designation, sex, salary);
	        staffService.addStaff(staff);
	        
	        idField.clear();
			nameField.clear();
			designationField.clear();
			sexField.clear();
			salaryField.clear();
		});
		
		
		VBox form = new VBox(
		        10,
		        idField,
		        nameField,
		        designationField,
		        sexField,
		        salaryField,
		        addButton
		    );

		    mainContent.getChildren().add(form);
	}
	// Event Listener on Button.onAction
	@FXML
	public void removeStaffClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void updateStaffClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void findStaffClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void searchStaffClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void displayAllStaffClicked(ActionEvent event) {
		mainContent.getChildren().clear();
		TableView<Staff> table = new TableView<Staff>();
		
		ArrayList<String> arr = staffService.getColumns();
		for (String datafield : arr) {
			TableColumn<Staff, String> column = new TableColumn<>(datafield.toUpperCase());
			column.setCellValueFactory(new PropertyValueFactory<>(datafield));
			table.getColumns().add(column);
		}
		
		
		table.setItems(FXCollections.observableArrayList(staffService.getStaff()));
		
		mainContent.getChildren().add(table);
	}
}
