package controller;

import javafx.fxml.FXML;
import services.StaffService;

import javafx.event.ActionEvent;

public class StaffController {
	private StaffService staffService;
	
	public void setHospitalManagement(HospitalManagement hospital) {
        staffService = new StaffService(hospital);
    }

	// Event Listener on Button.onAction
	@FXML
	public void addStaffClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void removeStaffClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void updateStaffClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void findStaffClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void searchStaffClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void displayAllStaffClicked(ActionEvent event) {
		// TODO Autogenerated
		staffService.displayAllStaff();
	}
}
